const CONDOMINIUM_PAYMENTS_SORT_BY_DATE = 'date';
const CONDOMINIUM_PAYMENTS_SORT_BY_VALUE = 'value';
const CONDOMINIUM_PAYMENTS_SORT_BY = [CONDOMINIUM_PAYMENTS_SORT_BY_DATE, CONDOMINIUM_PAYMENTS_SORT_BY_VALUE];

const FINE_SORT_BY_CREATED_AT = 'createdAt';
const FINE_SORT_BY_AMOUNT = 'amount';
const FINE_SORT_BY = [FINE_SORT_BY_CREATED_AT, FINE_SORT_BY_AMOUNT];

const REVIEW_SORT_BY_CREATED_AT = 'createdAt';
const REVIEW_SORT_BY_RATING = 'rating';
const REVIEW_SORT_BY = [REVIEW_SORT_BY_CREATED_AT, REVIEW_SORT_BY_RATING];

const ORDER_BY_ASC = 'asc';
const ORDER_BY_DESC = 'desc';
const ORDER_BY = [ORDER_BY_ASC, ORDER_BY_DESC];

export {
  CONDOMINIUM_PAYMENTS_SORT_BY_DATE,
  CONDOMINIUM_PAYMENTS_SORT_BY,
  ORDER_BY_ASC,
  ORDER_BY_DESC,
  ORDER_BY,
  FINE_SORT_BY,
  FINE_SORT_BY_CREATED_AT,
  REVIEW_SORT_BY,
  REVIEW_SORT_BY_CREATED_AT
};
