const CONDOMINIUM_PAYMENTS_SORT_BY_DATE = 'date';
const CONDOMINIUM_PAYMENTS_SORT_BY_VALUE = 'value';
const CONDOMINIUM_PAYMENTS_SORT_BY = [CONDOMINIUM_PAYMENTS_SORT_BY_DATE, CONDOMINIUM_PAYMENTS_SORT_BY_VALUE];

const ORDER_BY_ASC = 'asc';
const ORDER_BY_DESC = 'desc';
const ORDER_BY = [ORDER_BY_ASC, ORDER_BY_DESC];

export { CONDOMINIUM_PAYMENTS_SORT_BY_DATE, CONDOMINIUM_PAYMENTS_SORT_BY, ORDER_BY_ASC, ORDER_BY_DESC, ORDER_BY }