const STATUS_READY = 'READY'
const STATUS_MANUT = 'MANUT'
const STATUS_INACT = 'INACT'

const STATUS: string[] = [STATUS_READY,STATUS_MANUT,STATUS_INACT]

export{ STATUS_READY, STATUS_MANUT, STATUS_INACT, STATUS }