const STATUS_READY = 'READY';
const STATUS_MANUT = 'MANUT';
const STATUS_INACT = 'INACT';

const STATUS: string[] = [STATUS_READY, STATUS_MANUT, STATUS_INACT];

const STATUS_ORDER_PENDING = 'PENDING';
const STATUS_ORDER_IN_PROGRESS = 'IN_PROGRESS';
const STATUS_ORDER_COMPLETED = 'COMPLETED';
const STATUS_ORDER_CANCELLED = 'CANCELLED';
const STATUS_ORDER_VOTING = 'VOTING';

const STATUS_ORDER: string[] = [
  STATUS_ORDER_PENDING,
  STATUS_ORDER_IN_PROGRESS,
  STATUS_ORDER_COMPLETED,
  STATUS_ORDER_CANCELLED,
  STATUS_ORDER_VOTING,
];

const STATUS_RESERV_PENDING = 'PENDING';
const STATUS_RESERV_APPROVED = 'APPROVED';
const STATUS_RESERV_CANCELED = 'CANCELED';
const STATUS_RESERV_COMPLETED = 'COMPLETED';

const STATUS_RESERV: string[] = [
  STATUS_RESERV_PENDING,
  STATUS_RESERV_APPROVED,
  STATUS_RESERV_CANCELED,
  STATUS_RESERV_COMPLETED,
];

const STATUS_REQ_PENDING = 'PENDING';
const STATUS_REQ_APPROVED = 'APPROVED';
const STATUS_REQ_CANCELED = 'CANCELED';
const STATUS_REQ_COMPLETED = 'COMPLETED';

const STATUS_REQ: string[] = [STATUS_REQ_APPROVED, STATUS_REQ_PENDING, STATUS_REQ_CANCELED, STATUS_REQ_COMPLETED];

const STATUS_ORDERWORK_PENDING = 'PENDING';
const STATUS_ORDERWORK_IN_PROGRESS = 'IN_PROGRESS';
const STATUS_ORDERWORK_ON_HOLD = 'ON_HOLD';
const STATUS_ORDERWORK_REVIEW = 'REVIEW';
const STATUS_ORDERWORK_COMPLETED = 'COMPLETED';
const STATUS_ORDERWORK_CANCELLED = 'CANCELLED';
const STATUS_ORDERWORK_REJECTED = 'REJECTED';

const STATUS_ORDERWORK: string[] = [
  STATUS_ORDERWORK_PENDING,
  STATUS_ORDERWORK_IN_PROGRESS,
  STATUS_ORDERWORK_ON_HOLD,
  STATUS_ORDERWORK_REVIEW,
  STATUS_ORDERWORK_COMPLETED,
  STATUS_ORDERWORK_CANCELLED,
  STATUS_ORDERWORK_REJECTED,
];

export {
  STATUS_READY,
  STATUS_MANUT,
  STATUS_INACT,
  STATUS,
  STATUS_ORDER_PENDING,
  STATUS_ORDER_IN_PROGRESS,
  STATUS_ORDER_COMPLETED,
  STATUS_ORDER_CANCELLED,
  STATUS_ORDER_VOTING,
  STATUS_ORDER,
  STATUS_RESERV_PENDING,
  STATUS_RESERV_APPROVED,
  STATUS_RESERV_CANCELED,
  STATUS_RESERV_COMPLETED,
  STATUS_RESERV,
  STATUS_REQ_PENDING,
  STATUS_REQ_APPROVED,
  STATUS_REQ_CANCELED,
  STATUS_REQ_COMPLETED,
  STATUS_REQ,
  STATUS_ORDERWORK,
};
