const STATUS_READY = 'READY';
const STATUS_MANUT = 'MANUT';
const STATUS_INACT = 'INACT';

const STATUS: string[] = [STATUS_READY, STATUS_MANUT, STATUS_INACT];

const STATUS_ORDER_PENDING = 'PENDING';
const STATUS_ORDER_IN_PROGRESS = 'IN_PROGRESS';
const STATUS_ORDER_COMPLETED = 'COMPLETED';
const STATUS_ORDER_CANCELLED = 'CANCELLED';
const STATUS_ORDER_VOTING = 'VOTING';

const STATUS_ORDER: string[] = [
  STATUS_ORDER_PENDING,
  STATUS_ORDER_IN_PROGRESS,
  STATUS_ORDER_COMPLETED,
  STATUS_ORDER_CANCELLED,
  STATUS_ORDER_VOTING,
];

export {
  STATUS_READY,
  STATUS_MANUT,
  STATUS_INACT,
  STATUS,
  STATUS_ORDER_PENDING,
  STATUS_ORDER_IN_PROGRESS,
  STATUS_ORDER_COMPLETED,
  STATUS_ORDER_CANCELLED,
  STATUS_ORDER_VOTING,
  STATUS_ORDER,
};
