const URGENCY_LOW = 'LOW';
const URGENCY_MEDIUM = 'MEDIUM';
const URGENCY_HIGH = 'HIGH';

const URGENCY_LEVELS: string[] = [URGENCY_LOW, URGENCY_MEDIUM, URGENCY_HIGH];

export { URGENCY_LOW, URGENCY_MEDIUM, URGENCY_HIGH, URGENCY_LEVELS };
